[project]
name = "cmdstore"
version = "0.4.0"
description = "A CLI tool to store and retrieve commands with fuzzy finding"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [{ name = "Jakeer C", email = "jakeer.builds@gmail.com" }]
keywords = ["cli", "store", "fzf", "developer", "DX"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = ["pyperclip>=1.11.0"]


[project.scripts]
cmdstore = "cmdstore:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP", "B", "SIM"]
# Exclude some directories
exclude = [".venv", "__pycache__", "migrations"]

# Format imports automatically
[tool.ruff.isort]
known-first-party = ["src"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true

[dependency-groups]
dev = ["twine>=6.2.0"]
